version: "3.9"
services:
  app:
    build: ./app
    networks:
      - backend
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro 
      
networks:
    backend:
        driver: bridge
