version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflask
      MYSQL_USER: william
      MYSQL_PASSWORD: 1234will
    volumes:
      - ./docker/data/db:/var/lib/mysql
